### ISSUE TITLE
mapa mental Jordan

### ISSUE THREAD

**Issue by JordanMendoza401** [SistemasTecTlaxiaco/actividad-4-mapa-mental-JordanMendoza401#2]
![CONJUNTOS_Jordan](https://github.com/user-attachments/assets/869f2549-c029-4ce6-b254-4ee58ebc891a)

**Comment by KarenIMont** [comment]
Manejo Conceptual y Dominio del Tema: 5/5
Relación entre los Conceptos Incluidos en el Mapa: 5/5
Calidad de la Presentación: 5/5
Jerarquía de temas: 5/5
CALIFICACIÓN FINAL: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
